name: "Pre Release"

on:
  push:
    branches:
      - "master"
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Replace for your build process
      - name: "Build & test"
        run: |
          echo 'Released version ${{ github.ref }}' > Release.txt

      # Add the artifacts to include in the release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            Release.txt
            README.md
