name: Push documentation to docs repo

on:
  workflow_call:
    inputs:
      path-to-push:
        required: true
        type: string
      path-to-copy:
        required: false
        default: 'docs/'
        type: string
      repo-to-push:
        required: false
        default: 'docs'
        type: string
      branch-to-clone:
        required: false
        default: 'master'
        type: string
    secrets:
      API_TOKEN_GITHUB:
        required: true
  workflow_dispatch:

jobs:
  push-to-docs:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Pushes to nevermined.io/docs repository
        run: |
          git clone --branch ${{ inputs.branch-to-clone }} https://nvm-bot:${{ secrets.API_TOKEN_GITHUB }}@github.com/nevermined-io/${{ inputs.repo-to-push }}.git ../_docs
          cd ../_docs
          mkdir -p ${{ inputs.path-to-push }}
          cp -rf ../${{ env.REPOSITORY_NAME }}/${{ inputs.path-to-copy }}* ${{ inputs.path-to-push }} || true
          git config --global user.email "robot@robot.com"
          git config --global user.name "Robot"
          git add .
          # If there are no changes, git commit returns 1
          git commit -m "Update ${{ env.REPOSITORY_NAME }} docs" || true
          git push -f https://nvm-bot:${{ secrets.API_TOKEN_GITHUB }}@github.com/nevermined-io/${{ inputs.repo-to-push }}.git
